name: trackcorona
description: An application that tracks corona infected patients .

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.8.2
  cupertino_icons: ^0.1.3
  flutter_native_splash: ^0.1.9
  flutter_map_marker_cluster: ^0.2.7
  gps: ^0.1.1
  flutter_bloc: ^3.2.0
  meta: ^1.1.8
  equatable: ^1.1.1
  custom_radio_grouped_button: ^1.0.0
  toggle_switch: ^0.1.4
  awesome_dialog: ^0.1.4
  card_settings: ^1.8.1
  universal_html: ^1.2.2
#  user_location: ^0.1.2
  firebase_messaging: ^6.0.13
  location: ^3.0.2
  expandable: ^4.1.3
  flutter_form_bloc: ^0.13.1
  wc_form_validators: ^0.1.1
#  admob_flutter: ^0.3.4
  flutter_local_notifications: ^1.4.3
  social_share: ^2.0.4
  background_location: ^0.0.9+3
  map_controller: ^0.7.1
  dio: ^3.0.9
  jiffy: ^3.0.1
  connectivity: ^0.4.8+2
  get: 1.14.1-dev
  fab_circular_menu: ^1.0.0
  screenshot: ^0.1.1
#  http: ^0.12.0+4
  shared_preferences: ^0.5.7
#  status_alert: ^0.1.2
  shared_preferences_web: ^0.1.2+4
#  flutter_secure_storage: ^3.3.2

  line_awesome_icons: ^1.0.4+2
  getflutter: ^1.0.11
  json_annotation: ^3.0.1
#  dio_flutter_transformer: ^3.0.2
#  dio_http2_adapter: ^1.0.0
  get_it: ^4.0.1
  animated_splash: ^1.0.0
#  uuid: ^2.0.4
#  geocoder: ^0.2.1
#  flutter_spinkit: ^4.1.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  build_runner: ^1.9.0
  flutter_launcher_icons: ^0.7.5

  # For logo creation
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/dodgecorona_logo_simple.png"
  image_path_android: "assets/images/dodgecorona_logo_simple_curved.png"
  image_path_ios: "assets/images/dodgecorona_logo_simple.png"
  ios_path_web: "assets/images/dodgecorona_logo_simple.png"



# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/corona_splash_screen_image.png
    - assets/images/
    - assets/images/landing_page/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Alegreya
       fonts:
         - asset: assets/fonts/Alegreya-BoldItalic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
